# Numpy (datascienceschool.net)

## Numpy Array

list = 데이터타입 모두 가능, 크기 다양..포인터가 들어가있어서 할때마다 불러와야해서 느림
np.array = 자료형동일, 크기변경안됨... 대신 땋뙇뙇 들어가 있어서 초빠름
       >(파이썬으로만든게 아닌, C랭기지로 만든것! )  
       >(속도는 엄청 빠름.))  

In [1]:
# 리스트와 넘파이 어레이 속도 비교
import numpy as np #(np뒤에 페이스 꼭 하나 띄기)
np_arr = np.arange(100000)
nu_list = [i for i in range(100000)]

In [26]:
%%time     #(매직명령어 %%time 셀이돌아가는 시간을 알려준다)
for i in range(100): #돌아가는시간 100번만 사용
    sum(nu_list)            
#에러 왜 났니 ..ㅠㅠ  UsageError: Can't use statement directly after '%%time'!
#교수님결과값: Wall time 166ms

UsageError: Can't use statement directly after '%%time'!


In [27]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 152 ms


In [28]:
%%time
for i in range(100):
    np.sum(np_arr)
#오 에러안났구먼^^ 결과값:Wall time: 7 ms

Wall time: 47 ms


넘파이로 할 수 있는것 (일단. 매트릭스 행렬배열 연산을위한것)  
>y=ax+b (1차원)  
>Y=W.X+b 같은데 차원이 다른이야기(n차원) weight bias  


배열다루기  
통계낼수있음  
랜덤모듈대신에 넘파이안에있는 서브패키지안에 랜덤패키지 사용가능.  
서브패키지 안에 선형대수있음.   

## 1차원 배열 만들기...백터

In [4]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  #리스트가 들어왔다
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(ar)
#numpy.ndarray  로테이션이x돈다돈다~ 위에10개를 Y=W.X+b 같단하게표기한것.

numpy.ndarray

In [6]:
ar.shape  #(10,)숫자1개있어서 1차원, 뒤에 숫자붙으면 2차원, 3차원 들어나는것 백터..?스칼라..? 눼?

(10,)

## 백터화 연산

In [7]:
al = [2 * i for i in range(10)]
al

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
2 * ar  #이렇게쓰면 그냥 2배가 됩니다. ar 통으로 묶어서 두배로 만들어라! 이것이 "백터화연산" 넘파이 안에서만 가능한 일..

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
2 * al  #이건 리스트를 두번 반복할뿐. 값을 곱해주지 않는다.

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [11]:
2 * a + b

array([12, 24, 36])

In [12]:
a == 2  #각각의 엘리먼트에 대해서 통채로 백터화연산! 한방에! 할 수 있다 오.. 편한기능이구만!

array([False,  True, False])

In [13]:
b > 15  #비교연산에도 사용할 수 있다

array([False,  True,  True])

In [14]:
(a == 2) & (b > 10)  #논리식에도 적용할 수 있다

array([False,  True, False])

## 2차원배열(matrix)....1차원은백터

In [15]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c
#레인지안쓰고 왜이렇게 만들지? 생각하지말고- 뒤에배울꺼임
#리스트로 써주면 그것이 곧 배열이 되어 나온다규~ 

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
c.shape  #행이2개 열이3개라는 뜻 (2,3)

(2, 3)

In [17]:
len(c), len(c[0]) # 행열 구하는걸 이렇게 써도 되긴하는데 이렇게 많이 안쓰고 넘파이에서는 shape을 쓴다

(2, 3)

## 3.1넘파이배열 연습문제1

In [18]:
x = np.array([[10, 20, 30, 40], [50, 60, 70, 80]]) 
x

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [19]:
np.arange(10, 90, 10).reshape(2,-1)  #위처럼 해도되지만 이것처럼 할것이다 앞으로 ㅋ

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원배열만들기

In [20]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array   큰묶음2개*리스트3개*안쪽
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [21]:
d.shape, d.ndim #쉐입 갯수가 차원ndim이 된다 (3차원)

((2, 3, 4), 3)

## 배열의 인덱싱  막강한기능!!!!!

In [29]:
a = np.array([0, 1, 2, 3, 4])
a[2]   #1차원에서는 기존 알고있던것과 똑같

2

In [30]:
a[-1]

4

In [31]:
a = np.array([[0, 1, 2], [3, 4, 5]]) #2차원에서는 좀 다르다 3을 꺼내오고싶다면,
a[1][0]                       #기존리스트에서 이렇게 해도 3이나오긴하는데

3

In [32]:
#넘파이에서는 이렇게 쓴다   컴마만 찍으면 되서 편해짐!
a[1, 0]

3

## 배열슬라이싱 !!!엄청중요!!!!!

In [33]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
a[:, 1:3]  #행은 전부 다 :  열은 두개만해서 1:3  
#슬라이싱 빛을 발하는 순간이다!!!!!!!!!!!! 외워둬라!!!!

array([[1, 2],
       [5, 6]])

## 3.1넘파이배열 연습문제2

In [36]:
m = np.array([[ 0,  1,  2,  3,  4],  
            [ 5,  6,  7,  8,  9],  
            [10, 11, 12, 13, 14]])  

In [37]:
m[1, 2]

7

In [38]:
m[2, 4]

14

In [39]:
m[1, 1:3]

array([6, 7])

In [40]:
m[1:, 2]

array([ 7, 12])

In [42]:
m[:2, 3:]

array([[3, 4],
       [8, 9]])

## 배열 인덱싱 = 센싱인덱싱

In [49]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]  #값이 트루인놈만 나온다!!!!!!! 우앙~_~

array([0, 2, 4, 6, 8])

In [45]:
a % 2  #나머지는 0아니면 1이 나온다 그래서 

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [46]:
a % 2 == 0  #그래서 트루폴스값가능

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [47]:
a[a % 2 == 0]  #또 그래서 ㅋ 이렇게 처음부터 찍어도 됨

array([0, 2, 4, 6, 8])

In [48]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]   # 0,2,4,6,8 자리의 값만 출력

array([11, 33, 55, 77, 99])

In [50]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a                              #3*4 2차원행렬이다.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
a[:, [True, False, False, True]]      #행은 전부: 트루인값만 나온것임

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [53]:
a[[2, 0, 1], :]  #순서를 바꿀수도있다. 응????????ㅋㅋㅋ

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

## 3.1넘파이배열 연습문제3

In [54]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [57]:
#3의 배수를 찾아라
x[x % 3 == 0]     

array([ 3,  6,  9, 12, 15, 18])

In [58]:
#4로 나누면 1이 남는 수를 찾아라
x[x % 4 == 1]  

array([ 1,  5,  9, 13, 17])

In [60]:
#이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x[(x % 3 == 0) & (x % 4 == 1)]  

array([9])