# 3.2 배열의 생성과 변형

In [1]:
import numpy as np

## 넘파이의 자료형

In [2]:
x = np.array([1, 2, 3])  #정수는 인테저가 32구나
x.dtype

dtype('int32')

In [3]:
x = np.array([1.0, 2.0, 3.0])  #실수는 인테저가 64구나
x.dtype

dtype('float64')

In [4]:
x = np.array([1, 2, 3.0])  #섞여있으면 float64
x.dtype

dtype('float64')

In [5]:
x = np.array([1, 2, 3], dtype='float32')  #타입을 지정은 한번에 확실하기. 접두사쓰지말고..;;
x.dtype

dtype('float32')

## Inf( np.inf(infinity) 1을 0으로 나누면 무한대)와   
## Nan( np.nan(not a number)) 숫자로 정의할 수 없다

In [6]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
# 0, 무한대, 마이너스무한대, 숫자로 정의할 수 없다

array([  0.,  inf, -inf,  nan])

In [7]:
np.log(0) # 로그값의 0함수면 ... 마이너스인피티니 (로그함수 ) @_@

-inf

In [8]:
np.exp(-np.inf)  # 지수함수의 뒷자락 0으로 간다공..........@_@

0.0

## 배열생성 (몇가지 명령어)

In [9]:
#zeros명령어
np.zeros(5)  #5개를 만들겠다. 넘파이에서는 기본적인 데이터타입이 플롯이라서 0. 이게 5개나옴 ㅋ

array([0., 0., 0., 0., 0.])

In [10]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [11]:
a.dtype    #넘파이에서는 기본적인 데이터타입이 플롯이라서 0. 이게 5개나옴 ㅋ 기본은 '실수'다

dtype('float64')

In [12]:
b = np.zeros((2,3))
b                     #쉐입을 줄 수도 있다.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
c = np.zeros((2, 5), dtype="int")  #데이터타임 인트 주니까 
c

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
c.dtype          #인트32로 만들어짐

dtype('int32')

In [15]:
#0이 아닌 1로 초기화된 배열을 생성하려면 ones 명령

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
#ones_like, zeros_like 명령
np.ones_like(b)   #크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 생성하고 싶다aus


array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# 배열의 크기가 큰놈이면.. 초기화하는데 시간이 오래걸린다.. 이걸 막아주는것 np.empty
g = np.empty((4,3))
g                  #찌꺼기가 남아있더라도 채워넣으면 되서.. empty로 만들기도 한다.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# 가장많이 사용하는 명령어 arange 어레인지아니고 에이레인지
# 쉽게만들 수 있는 명령어
np.arange(10)                  # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(3, 21, 2)          # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
# linespace  
# 0부터 100까지 5단계의 값 linespace  
# (4분인수라고 하기도 한다..)점이 균일하지않을 때, 25% 50% 지점을 알려줌. 
# 시그모이드그래프(인공지능할떄 많이사용) 신기방기+_+ sigmoid
# x = np.linespace(-5,5,100)
# y = 1/(1+np.exp(-x))
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [22]:
# logspace
np.logspace(0.1, 1, 10)   #0.1부터 1까지 10단계로 나눠라..

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [23]:
np.log(np.logspace(0.1, 1, 10))  #로그를 씌우면 간격이 일정해짐

array([0.23025851, 0.46051702, 0.69077553, 0.92103404, 1.15129255,
       1.38155106, 1.61180957, 1.84206807, 2.07232658, 2.30258509])

## 전치연산 (transpose) 
행과 열을 바꾸는 작업  
(매트릭스 곱셈할 때 쓰는 기능)    
m*n n*r  n이 같아야 곱할수있다. 결과는 m*r  
2\*3 3\*2  그래서 곱할 수 있다.  
... 나중에 나오겠지만 A.T@A  
... np.dot(A.T,A)  

In [24]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
#위처럼 생긴걸 행과열을 바꾸어준다  (누워있는걸 세워줌 )
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
A.T @ A

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [27]:
A @ A.T

array([[14, 32],
       [32, 77]])

걱정하지말아요.. 그대.. 원리를 알기위해서 행렬의 곱을 하지만  
인공지능할때는, 내가 수식을 써주는 일은 없다...   
단지, 쉐입이 m\*n n\*r 맞는지확인 해야함  n이 동일한지  
차원이 맞는지 2차원 매트릭스 Y=W.X+b  

## 배열의 크기 변형(reshape)

In [28]:
a = np.arange(12)  # 12개만들어지는걸 
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
b = a.reshape(3, 4)  #행3개 열4개 로 리쉐입해서 2차원으로 바꿔주었다
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
a.reshape(3, -1)  #만약 -1을 주면 갯수를 꽉채워서 만들라는소리~_~

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a.reshape(-1, 4)  #앞을 -1줘도 된다 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a.reshape(3, 2, -1)  #3차원만드는방법 행3개, 열2개, 끝은 몰라-1  나중에 많이 쓰는 방법

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [33]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
#2차원을 다시 1차원으로 만들어주는 명령어  flatten (또는 ravel)
b.flatten()  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
##########  조심해야할 것
x = np.arange(5)   #1차원
x

array([0, 1, 2, 3, 4])

In [36]:
x.reshape(1, -1)  # 2차원 (아래와 여기는 전치행렬사이 >_<)

array([[0, 1, 2, 3, 4]])

In [37]:
x.reshape(5, 1)  #2차원  (내적의 곱을 구하고싶어서 세운것이다>_<)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [38]:
x[:, np.newaxis]  #기본차원 두고:, 하나더만들어 newaxis

array([[0],
       [1],
       [2],
       [3],
       [4]])

## 배열연결

In [39]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [41]:
# a1, a2 둘을 합치려면..  뒤에다가 붙이려고  hstack 에이치스택
np.hstack([a1, a2])


array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [42]:
# 버티칼스택 vstack 위아래로 쌓는것.
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.vstack([b1, b2]) # 버티칼스택 vstack 위아래로 쌓는것.
# 행과열 쉐입이 같으면 행으로도 열로도 쌓을 수 있는데
# 쉐입이 같지 않으면 ..? 어떻게 되나?

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
# 깊이 3차원으로 쌓는다. dstack 
# ...교수님 설명 ㄴㄴ

In [66]:
## 연습문제 3.2.1
x1 = np.zeros((3, 3))
x1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [67]:
x2 = np.ones((3, 2))
x2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [68]:
x3 = np.hstack([a1, a2])
x3

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [70]:
z1 = np.arange(10, 160, 10)  
z1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [75]:
z1.reshape(3, 5)


array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [76]:
z2 = z1.reshape(3, -1)
z2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [78]:
xz = np.vstack([x3, z2]) 
xz

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [82]:
xzxz = np.vstack([xz]*2)
xzxz

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [83]:
xzxz = np.vstack([xz, xz])
xzxz

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

## 2차원 그리드 포인트(격자점) 생성 



In [78]:
x = np.arange(3)
x

array([0, 1, 2])

In [79]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [80]:
# 격자점 15개 생성하는 방법
X, Y = np.meshgrid(x, y)

In [82]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [83]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [84]:
[list(zip(x, y)) for x, y in zip(X, Y)] #  zip함수를 썼다. 점15개 나옴

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]