# 3.3 배열의 연산

In [2]:
import numpy as np

## 백터화 연산

In [3]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [4]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 7 ms


In [5]:
%%time
z = x + y   #위에꺼보다 초초초빠름 순신간에 계산

Wall time: 999 µs


In [6]:
#위 사칙연산뿐아니라 비교연산, 논리연산도 백터화 연산이 가능하다
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [7]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [8]:
# 배열이 3개일 때
np.all(a == b)  # 배열통채로 비교 a와 b가 같으냐 물으니 틀리다고 F

False

In [9]:
np.all(a == c)    ## 배열통채로 비교

True

In [10]:
a = np.arange(1, 11)
np.log(a)       # 자연로그이다 (상용로그아니고)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [11]:
np.log10(a)  # 사용로그이다

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

## 스칼라와 벡터/행렬의 곱셈

In [12]:
x = np.arange(10)
x     #1차원으로 있어서 백터이다.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
100 * x  #스칼라를 백터했다? (각각 엘리먼트에 곱해짐)

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [17]:
x = np.arange(12).reshape(3, 4)
x  #2차원으로 변경시킴

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
100 * x # 마찬가지로 각각 엘리먼트에 곱해짐

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 브로드캐스팅

In [21]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [22]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [23]:
x + y

array([1, 2, 3, 4, 5])

In [24]:
x + 1  #위와 값이 같다. 백터곱셈같이 더해지는거.. 
#차원이 같지않아도 +- 가능하다

array([1, 2, 3, 4, 5])

## 차원 축소 연산
최대/최소: min, max, argmin최소값의위치, argmax최대값의위치

통계: sum, mean평균, median중앙값, std표준편차, var분산

불리언: all(and같은), any(or같은)


In [29]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [30]:
x.sum()

6

In [32]:
np.sum(x, axis=0)  # axis=0열의 합   @_@헷갈리....
# x[0,0] x[1,0]
# x[0,1] x[1,1]

array([3, 3])

In [33]:
np.sum(x, axis=1) # axis=1행의 합   @_@헷갈리....

array([2, 4])

In [37]:
## 연습문제 3.3.1
x = np.linspace(1.0, 10.0, 30).reshape(5, 6).round(2)       #1.0부터 10.0까지 30등분, reshape 5*6행렬
x

array([[ 1.  ,  1.31,  1.62,  1.93,  2.24,  2.55],
       [ 2.86,  3.17,  3.48,  3.79,  4.1 ,  4.41],
       [ 4.72,  5.03,  5.34,  5.66,  5.97,  6.28],
       [ 6.59,  6.9 ,  7.21,  7.52,  7.83,  8.14],
       [ 8.45,  8.76,  9.07,  9.38,  9.69, 10.  ]])

In [39]:
# 전체의 최대값
x.max() 

10.0

In [49]:
#각 행의 합
x.sum(axis = 1)

array([10.65, 21.81, 33.  , 44.19, 55.35])

In [44]:
#각 행의 최대값 ???????
np.max(x, axis=1)

array([ 2.55,  4.41,  6.28,  8.14, 10.  ])

In [43]:
#각 열의 평균
np.mean(x, axis=0)

array([4.724, 5.034, 5.344, 5.656, 5.966, 6.276])

In [45]:
#각 열의 최소값
np.min(x, axis=0)

array([1.  , 1.31, 1.62, 1.93, 2.24, 2.55])

## 정렬

In [50]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [51]:
np.sort(a)      # axis=-1 또는 axis=1 과 동일 , 아래와 같다

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [52]:
np.sort(a, axis=1)  #위와 결과는 같다

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [53]:
np.sort(a, axis=0)  #열단위로 소팅되어 뒤집어졌다.

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [54]:
a   #a자체는 안바뀌었다.

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [55]:
a.sort()

In [56]:
a  #이러면 a자체가 바뀌어버린다.

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [ ]:
#순서만 알고 싶다면 argsort 명령