# 2.2 벡터와 행렬의 연산

In [3]:
import numpy as np

## 벡터와 벡터의 곱셈

벡터의 내적 (inner product)  
세로세로로 안곱해지니까  
뉘여!! 가로 세로 1\*3 3\*1 이렇게 만들어서   

In [5]:
x = np.arange(1, 4).reshape(3, 1)  #1~3까지 
x

array([[1],
       [2],
       [3]])

In [10]:
y = np.arange(4, 7).reshape(3, 1)
y

array([[4],
       [5],
       [6]])

In [11]:
# 이상태에서 인너프로덕트를 해보자
x.shape, y.shape  #이상태에서는 벡터내적을 할 수없다.

((3, 1), (3, 1))

In [12]:
x.T.shape #그래서 이렇게 바꿔줌

(1, 3)

In [14]:
Z = x.T @ y
Z

array([[32]])

In [15]:
z.shape

(1, 1)

In [16]:
z[0,0]

32

In [17]:
np.dot(x.T, y)

array([[32]])

In [18]:
# 화이트보드 사진찍음......
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
x @ x.T

array([[14, 32],
       [32, 77]])

In [21]:
np.dot(x, y)

array([[32],
       [77]])

In [26]:
#포룩으로 할수있따...교수님어렵
def mat_mul(x, y):
    z = np.zeros((len(x), len(y[0])))

In [28]:
# 연습문제 2.2.1
p = np.array([100, 80, 50]) * 10000
p = p.reshape(1, 3)

In [29]:
n = np.array([3,4,5]).reshape(3, 1)

In [30]:
money = (p @ n)[0, 0]   #p n을 곱해서 0번째 수를 꺼냄.
money

8700000

In [ ]:
#연습문제 2.2.4

In [32]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
AB = A @ B
AB

array([[22, 28],
       [49, 64]])

In [33]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
BA = B @ A
BA

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [34]:
A = np.array([1, 2, 3])
B = np.array([[4, 7], [5, 8], [6, 9]])
AB = A @ B
AB
# 1*3 3*2 이여서 AB계산됐으나, 3*2 1*3 BA는 계산안됨.

array([32, 50])

In [37]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
AB = A @ B
AB

array([[19, 22],
       [43, 50]])

In [38]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
BA = B @ A
BA

array([[23, 34],
       [31, 46]])