In [13]:
import numpy as np

In [14]:
# 1.길이가 10인 0-벡터를 만들기.
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# 2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터만들기.
a2 = np.eye(1, 10, k=4)[0]
a2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [16]:
# 3. 10부터 49까지의 값을 가지는 벡터 만들기.
a3 = np.arange(10,50)
a3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
# 4. 위(3번) 벡터의 순서를 바꾸기.
a4 = a3[::-1]
a4

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [10]:
# 5. 0부터 8까지의 값을 가지는 3x3 행렬 만들기
f = np.arange(0,9).reshape(3,3)
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
# 6. 벡터[1,2,0,0,4,0]에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만들기
a = np.arange(0,5)
a[(a != 0) & (a != 3)]

array([1, 2, 4])

In [21]:
# 7. 3x3 단위행렬identity matrix 만들기
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# 8. 난수 원소를 가지는 3x3 행렬 만들기
a = np.random.rand(9).reshape(3,3).round(3)
a

array([[0.324, 0.123, 0.892],
       [0.271, 0.977, 0.78 ],
       [0.887, 0.9  , 0.211]])

In [27]:
# 9. 위 8번에서 만든 난수 행렬에서 최대값/최소값 원소를 찾기
a.max(),a.min()

(0.977, 0.123)

In [28]:
# 10 위 8번에서 만든 난수 행렬에서 행 평균, 열 평균을 계산
a.mean(axis=1), a.mean(axis=0)

(array([0.44633333, 0.676     , 0.666     ]),
 array([0.494     , 0.66666667, 0.62766667]))